// <auto-generated />
namespace ServiceStreamliningTheProductionProcess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixedtypeinpropertsModuleNameinSearchHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedtypeinpropertsModuleNameinSearchHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202011101208035_Fixed type in properts ModuleName in SearchHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
